# ===================================================================
# Configuración Spring Boot
#
# Configuración para el profile de Spring "dev".
# Aquí puedes establecer la configuración necesaria para el perfil de
# desarrollo.
# ===================================================================

# ===================================================================
# Propiedades estandar de Spring.
# Referencia completa en:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
    port: 8085
management:
    shell:
        ssh:
            port: 2085

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/sivad-motor-valuacion?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password:
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

# ===================================================================
# Propiedades especificas de la aplicacion (microservicio)
# ===================================================================
