spring:
  jpa:
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      hibernate.cache.use_minimal_puts: true

# ===================================================================
# Propiedades especificas de la aplicacion (microservicio)
# ===================================================================
info:
  arquetipo:
    version: #nmp.arquetipo.version#
  microservicio:
    nombre: #name#
    version: #version#
    descripcion: #description#
  spring-boot:
    version: #parent.version#

cxf:
  path: /soap-api

valuacion:
  referencia:
    alhaja:
        wsdlLocation: http://localhost:8084/soap-api/ReferenciaAlhajaService?wsdl
    diamante:
        wsdlLocation: http://localhost:8084/soap-api/ReferenciaDiamanteService?wsdl
    header:
        api:
          name: X-IBM-Client-Id
          key: 214943ce-5f1f-4329-976b-b711995bc89b
  avaluo:
    redondeo: DOS_DECIMALES_ROUND_HALF_UP

servicio:
  parametros:
    valor:
      filtros:
        baseUrl: http://localhost:8080/parametro/valor/filtros/{tipo}/{abreviatura}
    header:
      api:
        name: X-IBM-Client-Id
        key: xXx

# mostrar o no mensajes soap entrantes y salientes
soap:
  mensaje:
    mostrar: false
