DROP TABLE IF EXISTS JOURNAL_EVENT;
CREATE TABLE JOURNAL_EVENT
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    PRINCIPAL VARCHAR(50) NOT NULL,
    DATE TIMESTAMP,
    TYPE VARCHAR(255),
    PRIMARY KEY (ID)
);


DROP TABLE IF EXISTS JOURNAL_ENTITY_EVENT;
CREATE TABLE JOURNAL_ENTITY_EVENT
(
    ID BIGINT NOT NULL,
    CLASS VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE JOURNAL_ENTITY_EVENT ADD FOREIGN KEY (ID) REFERENCES JOURNAL_EVENT (ID);


DROP TABLE IF EXISTS JOURNAL_CUSTOM_EVENT;
CREATE TABLE JOURNAL_CUSTOM_EVENT
(
    ID BIGINT NOT NULL,
    COMMENT VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE JOURNAL_CUSTOM_EVENT ADD FOREIGN KEY (ID) REFERENCES JOURNAL_EVENT (ID);


DROP TABLE IF EXISTS JOURNAL_EVENT_DATA;
CREATE TABLE JOURNAL_EVENT_DATA
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    EVENT BIGINT NOT NULL,
    PROPERTY VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);
ALTER TABLE JOURNAL_EVENT_DATA ADD FOREIGN KEY (EVENT) REFERENCES JOURNAL_EVENT (ID);


DROP TABLE IF EXISTS TC_POLITICA_CASTIGO_PIEZA;
CREATE TABLE TC_POLITICA_CASTIGO_PIEZA
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    FECHA_LISTADO TIMESTAMP NOT NULL
);
ALTER TABLE TC_POLITICA_CASTIGO_PIEZA ADD CONSTRAINT PK_TC_POLITICA_CASTIGO_PIEZA_ID PRIMARY KEY(ID);

CREATE INDEX IDX_TC_POLITICA_CASTIGO_PIEZA_ID ON TC_POLITICA_CASTIGO_PIEZA(ID);
CREATE INDEX IDX_TC_POLITICA_CASTIGO_PIEZA_FECHA_LISTADO ON TC_POLITICA_CASTIGO_PIEZA(FECHA_LISTADO);

DROP TABLE IF EXISTS TC_POLITICA_CASTIGO_PIEZA_FACTORES;
CREATE TABLE TC_POLITICA_CASTIGO_PIEZA_FACTORES
(
    ID BIGINT AUTO_INCREMENT NOT NULL,
    POLITICA BIGINT NOT NULL,
    PIEZA VARCHAR(255) NOT NULL,
    FACTOR DECIMAL(4, 4) NOT NULL
);
ALTER TABLE TC_POLITICA_CASTIGO_PIEZA_FACTORES ADD CONSTRAINT PK_TC_POLITICA_CASTIGO_PIEZA_FACTORES_ID PRIMARY KEY(ID);

ALTER TABLE TC_POLITICA_CASTIGO_PIEZA_FACTORES ADD FOREIGN KEY (POLITICA) REFERENCES TC_POLITICA_CASTIGO_PIEZA (ID);
