INSERT INTO TC_POLITICA_CASTIGO_PIEZA(ID, FECHA_LISTADO) VALUES (1,  '2017-01-02 22:18:36.000');
INSERT INTO TC_POLITICA_CASTIGO_PIEZA_FACTORES(POLITICA, PIEZA, FACTOR)
VALUES (1, 'mx.com.nmp.ms.sivad.valuacion.dominio.modelo.Diamante', 0.3);
INSERT INTO TC_POLITICA_CASTIGO_PIEZA_FACTORES(POLITICA, PIEZA, FACTOR)
VALUES (1, 'mx.com.nmp.ms.sivad.valuacion.dominio.modelo.Complementario', 0.4000);
INSERT INTO TC_POLITICA_CASTIGO_PIEZA_FACTORES(POLITICA, PIEZA, FACTOR)
VALUES (1, 'mx.com.nmp.ms.sivad.valuacion.dominio.modelo.Alhaja', 0.4000);

INSERT INTO TC_POLITICA_CASTIGO_PIEZA(ID, FECHA_LISTADO) VALUES (2,  '2017-01-02 22:01:36.000');
INSERT INTO TC_POLITICA_CASTIGO_PIEZA_FACTORES(POLITICA, PIEZA, FACTOR)
VALUES (2, 'mx.com.nmp.ms.sivad.valuacion.dominio.modelo.Diamante', 0.3321);
INSERT INTO TC_POLITICA_CASTIGO_PIEZA_FACTORES(POLITICA, PIEZA, FACTOR)
VALUES (2, 'mx.com.nmp.ms.sivad.valuacion.dominio.modelo.Complementario', 0.4237);
INSERT INTO TC_POLITICA_CASTIGO_PIEZA_FACTORES(POLITICA, PIEZA, FACTOR)
VALUES (2, 'mx.com.nmp.ms.sivad.valuacion.dominio.modelo.Alhaja', 0.4173);
